import os
import psycopg2

def get_db_connection():
    database_url = os.getenv("DATABASE_URL")
    conn = None
    if database_url:
        # Conexi√≥n para producci√≥n (Render, etc.)
        # print("üîó Conectando a la base de datos en la nube (Render)...")
        # El bloque try/except est√° en las rutas, as√≠ que aqu√≠ dejamos que el error se propague
        conn = psycopg2.connect(database_url, sslmode='require')
    else:
        # Conexi√≥n para desarrollo local
        # print("üíª Conectando a la base de datos local...")
        conn = psycopg2.connect(
            dbname=os.getenv("DB_NAME", "asistencia"),
            user=os.getenv("DB_USER", "postgres"),
            password=os.getenv("DB_PASSWORD", "acgc.2008"),
            host=os.getenv("DB_HOST", "localhost"),
            port=os.getenv("DB_PORT", "5432")
        )
    
    # print("‚úÖ Conexi√≥n a la base de datos establecida.")
    return conn
